version: '3'

services:
  api:
    container_name: agreena_api
    image: agreena_api:1.0.0
    restart: unless-stopped
    build:
      context: .
      target: api
      dockerfile: ./Dockerfile
    entrypoint: sh docker-entrypoint.sh
    env_file:
      - .production.env
    ports:
      - $PORT:$PORT
    networks:
      - agreena-network
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: agreena_db
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:alpine
    container_name: agreena_db
    restart: always
    networks:
      - agreena-network
    env_file:
      - .production.env
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD

  adminer:
    container_name: agreena_db_adminer
    image: adminer
    restart: always
    networks:
      - agreena-network
    env_file:
      - .production.env
    ports:
      - 8080:8080

networks:
  agreena-network:
    driver: bridge