module.exports = {
    development: {
        // username: process.env.DATABASE_USER,
        // password: process.env.DATABASE_PASSWORD,
        // port: process.env.DATABASE_PORT,
        // host: process.env.DATABASE_HOST,
        url: process.env.DATABASE_URL,
        dialect: process.env.DATABASE_DIALECT,
        database: process.env.DATABASE_NAME,
        seederStorage: 'sequelize',
        logging: true,
    },
    production: {
        // username: process.env.DATABASE_USER,
        // password: process.env.DATABASE_PASSWORD,
        // port: process.env.DATABASE_PORT,
        // host: process.env.DATABASE_HOST,
        url: process.env.DATABASE_URL,
        dialect: process.env.DATABASE_DIALECT,
        database: process.env.DATABASE_NAME,
        seederStorage: 'sequelize',
    },
    docker: {
        // username: process.env.DATABASE_USER,
        // password: process.env.DATABASE_PASSWORD,
        // port: process.env.DATABASE_PORT,
        // host: process.env.DATABASE_HOST,
        url: process.env.DATABASE_URL,
        dialect: process.env.DATABASE_DIALECT,
        database: process.env.DATABASE_NAME,
        seederStorage: 'sequelize',
    },
};