name: Deploy

on:
  push:
    branches:
      - master

jobs:
  check-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "api-agreena-api"
          heroku_email: "22usyk08@gmail.com"
          usedocker: true
